version: '3.6'
services:
  db:
    image: docker.io/library/mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: wordpress
  db_pma:
    image: docker.io/phpmyadmin/phpmyadmin:latest
    depends_on:
    - db
    ports:
    - 8082:80
    environment:
      MYSQL_ROOT_PASSWORD: password
      PMA_USER: root
      PMA_PASSWORD: password
  www:
    depends_on:
    - db
    build:
      context: ./.docker
    volumes:
    - ".:/var/www/html/wp-content/plugins/dummy-plugin"
    ports:
    - 8080:80
    - 8443:443
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: password
      WORDPRESS_DEBUG: 1
      WORDPRESS_CONFIG_EXTRA: |
        define( 'WP_ALLOW_MULTISITE', true );
